services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
        public: true

    Symfony\Component\Mailer\EventListener\MessageLoggerListener:
        public: true
